language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

scrip: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r springboot-project *
  - mkdir -p deploy
  - mv springboot-project.zip deploy/springboot-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-test-build-ti
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-test-build-ti
    key: springboot-project.zip
    bundle_type: zip
    application: springboot-test
    deployment_group: springboot-test-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - pro_cess@naver.com