language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

scrip: "./gradlew clean build"

notifications:
  email:
    recipients:
      - pro_cess@naver.com